name: Build Android App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: Set up JDK 17
      uses: actions/setup-java@v5.0.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.2

    # 使用 gradle/gradle-build-action 来设置 Gradle 环境
    # 这个 Action 会自动处理 Gradle Wrapper 的下载和缓存
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 7.5 # 明确指定 Gradle 版本，与 gradle-wrapper.properties 保持一致

    # 授予 gradlew 执行权限（仍然需要，因为 checkout 后可能丢失）
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK (Unsigned)
      # gradle/gradle-build-action 已经设置了 PATH，可以直接运行 gradlew
      run: gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-apk
        path: app/build/outputs/apk/debug/app-debug.apk
