name: Build Android App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 建议使用最新稳定版本，v4 是当前推荐的

    - name: Set up JDK 21
      uses: actions/setup-java@v4 # 建议使用最新稳定版本，v4 是当前推荐的
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.2

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    # 移除这一步，因为我们不使用项目内的 gradlew 脚本
    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew

    - name: Build Debug APK (Unsigned)
      # 关键更改：使用 'gradle' 命令而不是 'gradlew'
      run: gradle assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-apk
        path: app/build/outputs/apk/debug/app-debug.apk
